name: Test T417382
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '9.5'
        mysql database: 'test_db_wiki'
        mysql root password: 'root'
    - run: |
        mysql -uroot -proot test_db_wiki <<< 'SELECT 1;'
